'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Plus,MoveUpRight,Activity,Users,Route,ScanLine,Check,Image as ImageIcon} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Input} from '@/components/ui/input';
const needs=[['После операции','Вернуться к привычной активности и восстановить движение.'],['После травмы','Пройти путь восстановления с поддержкой команды.'],['Боль в спине и шее','Разобраться с болью, осанкой и ограничениями движения.'],['Спорт','Вернуться к тренировкам и любимым нагрузкам.'],['Сидячий образ жизни','Добавить движения и поработать с последствиями недостатка активности.'],['Дети и подростки','Реабилитация от 6 лет при хронических непрогрессирующих двигательных нарушениях.']];
const steps=[['Консультация','Знакомимся с вашей историей и определяем задачи.'],['Диагностика','Находим отправную точку для восстановления.'],['ЛФК','Работаем над движением вместе с реабилитологом.'],['Массаж и мануальная терапия','Работаем с мышцами и связками.'],['Физиотерапия','Подключаем аппаратные методы по показаниям.'],['Поддержка','Помогаем сохранить достигнутый результат.']];
const directions=[['Движение','Мобильность суставов, восстановление после протезирования, работа с мышцами и связками.'],['Боль','Спина, поясница, шея, суставы, мышцы, головные боли и мигрень.'],['После травм и операций','Послеоперационная реабилитация, сочетанные травмы, восстановление после аварий.'],['Спорт','Программы для профессиональных спортсменов и любителей.'],['Особые программы','Для детей, подростков и людей с хроническими непрогрессирующими двигательными нарушениями.']];
const groups=[['Врачи',['Травматолог-ортопед','Невролог','Терапевт']],['Реабилитация',['Специалист ЛФК','Спортивный реабилитолог']],['Восстановление',['Физиотерапевт','Массажист','Остеопат']]];
function Photo({label,className=''}:{label:string,className?:string}){return <div className={'placeholder '+className}><ImageIcon size={30} strokeWidth={1}/><span className="photo-label">{label}</span></div>}
function Heading({label,title,children}:{label:string,title:React.ReactNode,children?:React.ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div>{children}</div>}
export default function Content(){
 const [sent,setSent]=useState(false);
 useEffect(()=>{const items=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});items.forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);
 return <>
 <section className="section panel reveal" id="for-whom"><Heading label="Начните с себя" title={<>Что вас<br/><em>беспокоит?</em></>}><p>Вам не нужно знать, какой специалист нужен. Начните с того, что мешает двигаться свободно.</p></Heading><div className="needs-grid">{needs.map(([title,desc],i)=><a href="#contact" className={'need-card need-'+i} key={title}><span className="card-top">0{i+1}<ArrowUpRight size={22}/></span><div><h3>{title}</h3><p>{desc}</p></div></a>)}</div></section>
 <section className="intro reveal" id="about"><p className="eyebrow">О центре</p><h2>Восстановление<br/>начинается <em>с опоры.</em></h2><p>Когда движение ограничено, меняется качество жизни. Мы объединяем специалистов разных направлений, чтобы помочь вам снова быть активными и чувствовать себя свободнее.</p></section>
 <section className="why-grid reveal"><Photo label="Фото · работа специалиста с пациентом" className="why-photo"/><div className="why-main panel"><p className="eyebrow">Наш подход</p><h2>Одна проблема.<br/><em>Комплексное<br/>решение.</em></h2><p>Диагностика, лечение и восстановление — в одном специализированном центре.</p></div>{[[Users,'Командно','Специалисты разных направлений работают вместе.'],[ScanLine,'Персонально','Учитываем ваше состояние, задачи и динамику.'],[Route,'Последовательно','Сопровождаем и адаптируем программу по мере прогресса.']].map(([Icon,title,desc]:any)=><div className="value-card panel" key={title}><Icon size={26} strokeWidth={1.3}/><h3>{title}</h3><p>{desc}</p></div>)}</section>
 <section className="section route-section panel reveal" id="route"><Heading label="Ваш маршрут" title={<>Шаг за шагом.<br/>К привычной жизни.</>}><p>Программа подбирается индивидуально. Состав и последовательность методов зависят от консультации и показаний.</p></Heading><div className="route-grid">{steps.map(([title,desc],i)=><article key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div><a className="button light" href="#contact">Начать с консультации <ArrowUpRight size={18}/></a></section>
 <section className="section panel reveal" id="directions"><Heading label="Направления" title={<>Помогаем вернуть<br/><em>свободу движения.</em></>}/><Accordion className="directions">{directions.map(([title,desc],i)=><AccordionItem value={title} key={title}><AccordionTrigger><span className="direction-title"><small>0{i+1}</small>{title}</span></AccordionTrigger><AccordionContent><p>{desc}</p><a href="#contact" className="text-link">Обсудить со специалистом ↗</a></AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="section panel reveal" id="team"><Heading label="Специалисты" title={<>Ваша команда.<br/><em>Ваша опора.</em></>}><p>Разные специалисты. Одна цель — восстановление вашего движения.</p></Heading><Tabs defaultValue="Врачи"><TabsList className="team-tabs">{groups.map(([name])=><TabsTrigger key={name as string} value={name as string}>{name}</TabsTrigger>)}</TabsList>{groups.map(([name,roles])=><TabsContent value={name as string} key={name as string}><div className="team-grid">{(roles as string[]).map(role=><article className="person" key={role}><Photo label="Фото специалиста"/><p className="person-role">{role}</p><h3>Имя и фамилия</h3><p className="muted">Данные специалиста будут добавлены</p><details><summary>О специалисте <Plus size={16}/></summary><p>Здесь появятся стаж, специализация, образование и повышение квалификации.</p></details></article>)}</div></TabsContent>)}</Tabs></section>
 <section className="section panel reveal" id="space"><Heading label="Пространство центра" title={<>Всё для восстановления.<br/><em>В одном пространстве.</em></>}/><div className="space-grid"><Photo label="Фото · пространство центра" className="space-large"/><div className="space-stat"><b>03</b><h3>спортивных зала</h3><p>Для разных тренировок и групп пациентов.</p></div><div className="space-stat green-surface"><b>03</b><h3>массажных кабинета</h3><p>Для работы с мышцами и восстановления.</p></div><Photo label="Фото · оборудование"/><div className="space-small"><h3>Физиотерапия</h3><p>Отдельный кабинет для аппаратных методов восстановления.</p></div><div className="space-small"><h3>Процедурный кабинет</h3><p>Поддерживающие процедуры и тейпирование.</p></div></div></section>
 <section className="result panel reveal"><p className="eyebrow">То, ради чего мы работаем</p><h2>Больше движения.<br/>Больше <em>вашей жизни.</em></h2><div className="result-words"><span>Двигаться <MoveUpRight/></span><span>Укреплять <MoveUpRight/></span><span>Возвращаться <MoveUpRight/></span><span>Сохранять <MoveUpRight/></span></div></section>
 <section className="section panel reveal" id="reviews"><Heading label="Истории и отзывы" title={<>За каждым движением —<br/><em>своя история.</em></>}/><div className="review-grid"><Photo label="Фото / видео · история пациента"/><div className="review-placeholder"><span className="quote-mark">“</span><h3>Здесь будет история<br/>восстановления пациента</h3><p>Что беспокоило → как проходила работа → какой результат достигнут.</p><span className="muted">Добавим после получения подтверждённого отзыва.</span></div></div><div className="review-short">{[1,2].map(i=><div key={i}>Место для отзыва пациента <span>0{i}</span></div>)}</div></section>
 <section className="section panel reveal" id="prices"><Heading label="Стоимость" title={<>Начните<br/><em>с консультации.</em></>}><p>Персональная программа рассчитывается после знакомства с вашей задачей.</p></Heading><div className="prices-grid"><article className="price-card green-surface"><span className="eyebrow">Первый шаг</span><h3>Первичный приём</h3><p>Консультация специалиста и определение дальнейшего маршрута.</p><strong>Стоимость уточняется</strong><a href="#contact" className="button light">Узнать стоимость ↗</a></article><article className="price-card"><span className="eyebrow">Ваш маршрут</span><h3>Индивидуальная программа</h3><p>Состав, длительность и стоимость зависят от состояния и целей восстановления.</p><strong>После консультации</strong></article><article className="price-card"><span className="eyebrow">Регулярная работа</span><h3>Абонементы</h3><p>Для регулярных программ восстановления и поддержки результата.</p><strong>Подберём вместе</strong></article></div></section>
 <section className="section panel faq-section reveal" id="faq"><div><p className="eyebrow">Вопросы и ответы</p><h2>Давайте<br/><em>разберёмся.</em></h2><p>Самое важное перед первым обращением.</p></div><Accordion defaultValue={['0']}>{[
 ['Не знаю, к кому записаться. Что делать?','Начните с обращения в центр. Расскажите, что вас беспокоит, и мы поможем определить, с какого специалиста начать.'],
 ['Как проходит первая консультация?','Специалист знакомится с вашей историей и ограничениями движения, уточняет задачи и определяет дальнейшие шаги.'],
 ['Что взять с собой?','Если у вас есть заключения, выписки и результаты обследований, подготовьте их к консультации. Полный список необходимых документов уточним перед визитом.'],
 ['Как формируется программа?','Индивидуально: с учётом вашего состояния, задач и показаний. По мере восстановления программа может меняться.'],
 ['Можно ли заниматься детям?','В структуре центра предусмотрена реабилитация детей от 6 лет и подростков при хронических непрогрессирующих двигательных нарушениях. Возможность приёма обсудим индивидуально.'],
 ['Где посмотреть документы центра?','Лицензия, правила оказания услуг, согласия и другие документы появятся в разделе для пациентов после предоставления центром.']
 ].map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="section contact panel reveal" id="contact"><div><p className="eyebrow">Первый шаг — знакомство</p><h2>Верните себе<br/><em>свою опору.</em></h2><p>Оставьте контакты. Мы поможем определить, с чего начать восстановление.</p><span className="contact-arrow" aria-hidden="true">↗</span></div><div className="form-wrap">{sent?<div className="success" role="status"><span className="success-icon"><Check size={32}/></span><h3>Спасибо!<br/>Мы скоро с вами свяжемся.</h3><button className="text-link" onClick={()=>setSent(false)}>Вернуться к форме</button></div>:<form onSubmit={e=>{e.preventDefault();if(e.currentTarget.checkValidity()){e.currentTarget.reset();setSent(true)}}}><h3>Записаться на консультацию</h3><label htmlFor="phone">Номер телефона</label><Input id="phone" name="phone" type="tel" autoComplete="tel" placeholder="+7 (___) ___-__-__" required minLength={7} maxLength={25} pattern="[+0-9\\s\\(\\)\\-]{7,25}"/><label htmlFor="email">Электронная почта</label><Input id="email" name="email" type="email" autoComplete="email" placeholder="mail@example.ru" required/><button className="button green" type="submit">Свяжитесь со мной <ArrowUpRight size={19}/></button><p className="form-note">Демонстрационная форма. Данные не отправляются и не сохраняются.</p></form>}</div></section>
 <section className="section panel reveal" id="contacts"><Heading label="Контакты" title={<>Мы <em>рядом.</em></>}><p>Москва<br/>Адрес и удобный маршрут добавим позже.</p></Heading><div className="contacts-grid"><div className="map-placeholder"><span className="map-pin"><span/></span><p>Здесь будет карта проезда</p></div><div className="contact-details"><div><span>Адрес</span><p>Москва · адрес уточняется</p></div><div><span>Телефон и email</span><p>Контакты будут добавлены</p></div><div><span>Режим работы и парковка</span><p>Информация уточняется</p></div><a className="text-link" href="#contact">Задать вопрос ↗</a></div></div></section>
 <footer className="panel"><div className="footer-top"><a className="brand" href="#">ТОЧКА<br/>ОПОРЫ<span className="logo-slot">место для логотипа</span></a><p>Свобода движения<br/>с опорой на будущее.</p><a className="top-link" href="#" aria-label="Наверх">↑</a></div><div className="footer-links"><div><a href="#about">О центре</a><a href="#directions">Направления</a><a href="#team">Специалисты</a><a href="#space">Пространство</a></div><div><a href="#prices">Стоимость</a><a href="#reviews">Отзывы</a><a href="#faq">Вопросы и ответы</a><a href="#contacts">Контакты</a></div><div className="documents"><b>Пациентам</b><p>Лицензия · Оферта · Политика конфиденциальности · Обработка персональных данных · Согласия · Форма ИДС · Отказ от медицинского вмешательства</p><small>Документы будут добавлены.</small></div></div><div className="footer-bottom"><span>© 2026 Точка опоры</span><span>Центр комплексной реабилитации</span></div></footer>
 </>;
}
