'use client';
import {useEffect} from 'react';
import Brand from './brand';
import {ArrowUpRight,Plus,MoveUpRight,Activity,Users,Route,ScanLine,Image as ImageIcon} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {ContactButton} from './contact-dialog';
const needs=[['После операции','Вернуться к привычной активности и восстановить движение.'],['После травмы','Пройти путь восстановления с поддержкой команды.'],['Боль в спине и шее','Разобраться с болью, осанкой и ограничениями движения.'],['Спорт','Вернуться к тренировкам и любимым нагрузкам.'],['Сидячий образ жизни','Поработать с болью и ограничениями, которые мешают в течение рабочего дня.'],['Дети и подростки','Обсудить особенности движения и подходящую программу восстановления.'],['Старший возраст','Сохранить подвижность и самостоятельность в повседневных делах.'],['Ограничения подвижности','Найти подход к восстановлению с учётом возможностей здоровья.']];
const steps=[['Консультация','Врач определяет потребности пациента.'],['Диагностика','Определяем оптимальный путь восстановления.'],['ЛФК','Работа с опорно-двигательным аппаратом вместе с реабилитологом.'],['Массаж и мануальная терапия','Работа с мышцами и связками.'],['Физиотерапия','Использование аппаратных методов для закрепления результата.'],['Поддержка','Программы для сохранения достигнутых результатов.']];
const directions=[['Движение','Подвижность суставов, работа со стопами и кистями, восстановление после протезирования верхних и нижних конечностей.'],['Боль','Боль в спине, пояснице, шее, суставах, мышцах и связках; головная боль и мигрень.'],['После травм и операций','Послеоперационная реабилитация, сочетанные травмы, восстановление после аварий.'],['Спорт','Программы для профессиональных спортсменов и любителей.'],['Особые программы','Работа с нарушениями осанки и сколиозом. Программы для детей, подростков, людей старшего возраста и с ограничениями подвижности.']];
const groups: [string,string[]][]=[['Специалисты ЛФК',['Специалист ЛФК']],['Специалисты спортивной реабилитации',['Специалист спортивной реабилитации']],['Физиотерапевты',['Физиотерапевт']],['Травматологи',['Травматолог']],['Неврологи',['Невролог']],['Массажисты',['Массажист']],['Остеопаты',['Остеопат']],['Врачи-терапевты',['Врач-терапевт']]];
function Photo({label,className=''}:{label:string,className?:string}){return <div className={'placeholder '+className}><ImageIcon size={30} strokeWidth={1}/><span className="photo-label">{label}</span></div>}
function Heading({label,title,children}:{label:string,title:React.ReactNode,children?:React.ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div>{children}</div>}
export default function Content(){
 useEffect(()=>{const items=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});items.forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);
 return <>
 <section className="section panel reveal" id="for-whom"><Heading label="Начните с себя" title={<>Что вас<br/><em>беспокоит?</em></>}><p>Вам не нужно знать, какой специалист нужен. Начните с того, что мешает двигаться свободно.</p></Heading><div className="needs-grid">{needs.map(([title,desc],i)=><ContactButton className={'need-card need-'+i} key={title}><span className="card-top">0{i+1}<ArrowUpRight size={22}/></span><div><h3>{title}</h3><p>{desc}</p></div></ContactButton>)}</div></section>
 <section className="intro reveal" id="about"><p className="eyebrow">О центре</p><h2>Восстановление<br/>начинается <em>с опоры.</em></h2><p>Клинику «Точка опоры» основали врачи. Мы знаем, как боль и ограничения движения меняют привычную жизнь. Поэтому начинаем с вашей истории и того, что важно именно вам: снова ходить, работать, тренироваться или справляться с повседневными делами.</p></section>
 <section className="section panel usp-section reveal" id="approach"><Heading label="Почему Точка опоры" title={<>Полный путь восстановления.<br/><em>С опорой на вас.</em></>}><p>От определения причины до закрепления результата — в одном специализированном центре.</p></Heading><div className="usp-grid">{[
 ['01','Берёмся за сложные случаи','Занимаемся восстановлением движения во всех частях тела, в том числе при сложных и длительных ограничениях. Программу определяем с учётом вашего состояния.'],
 ['02','Все специалисты — в одном центре','Объединяем диагностику, лечение и укрепление достигнутого результата. Врачи и специалисты по реабилитации работают вместе в рамках вашего маршрута.'],
 ['03','Современное оборудование и методики','Используем современное медицинское оборудование и актуальные методики восстановления. Аппаратные процедуры подбираем по показаниям и включаем в общую программу.'],
 ['04','Сопровождаем на каждом этапе','Оцениваем прогресс и эффективность выбранного пути. Адаптируем и персонализируем программу по мере восстановления — с учётом ваших целей и изменений состояния.']
 ].map(([number,title,description])=><article className="usp-card" key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="section route-section panel reveal" id="route"><Heading label="Ваш маршрут восстановления" title={<>6 шагов к вашей<br/>жизни без боли.</>}><p>Ваш маршрут начинается с того, что мешает вам жить привычной жизнью. Состав и последовательность методов подбираем индивидуально. По мере восстановления оцениваем изменения и адаптируем программу.</p></Heading><div className="route-grid">{steps.map(([title,desc],i)=><article key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div><ContactButton className="button light">Начать с консультации <ArrowUpRight size={18}/></ContactButton></section>
 <section className="section panel reveal" id="directions"><Heading label="Направления" title={<>Помогаем вернуть<br/><em>свободу движения.</em></>}/><div className="directions">{directions.map(([title,desc],i)=><article className="direction-row" key={title}><span className="direction-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
 <section className="section panel reveal" id="team"><Heading label="Специалисты" title={<>Наша команда.<br/><em>Ваша опора.</em></>}><p>Состав команды зависит от вашей задачи. Специалисты разных направлений работают в рамках общей программы и помогают закрепить достигнутый результат.</p></Heading><Tabs defaultValue="Специалисты ЛФК"><TabsList className="team-tabs" aria-label="Специальности команды">{groups.map(([name])=><TabsTrigger key={name as string} value={name as string}>{name}</TabsTrigger>)}</TabsList>{groups.map(([name,roles])=><TabsContent value={name as string} key={name as string}><div className="team-grid">{(roles as string[]).map(role=><article className="person" key={role}><Photo label="Фото специалиста"/><p className="person-role">{role}</p><h3>Имя и фамилия</h3><p className="muted">Данные специалиста будут добавлены</p><details><summary>О специалисте <Plus size={16}/></summary><p>Здесь появятся стаж, специализация, образование, повышение квалификации, рассказ специалиста о своём подходе и информация о том, с кем он не работает.</p></details></article>)}</div></TabsContent>)}</Tabs></section>
 <section className="section panel reveal" id="space"><Heading label="Пространство центра" title={<>Всё для восстановления.<br/><em>В одном пространстве.</em></>}/><div className="space-grid"><Photo label="Фото · пространство центра" className="space-large"/><div className="space-stat"><b>03</b><h3>спортивных зала</h3><p>Для разных тренировок и групп пациентов.</p></div><div className="space-stat green-surface"><b>03</b><h3>массажных кабинета</h3><p>Классический, спортивный, лечебный, миофасциальный, расслабляющий и антицеллюлитный массаж. Также здесь проводят мануальную терапию, кинезиотерапию и остеопатию.</p></div><Photo label="Фото · оборудование"/><div className="space-small"><h3>Кабинет физиотерапии</h3><p>Оборудование для ударно-волновой терапии, магнитотерапии, электро- и фонофореза.</p></div><div className="space-small"><h3>Процедурный кабинет</h3><p>Поддерживающие процедуры и тейпирование.</p></div></div></section>
 <section className="result panel reveal"><p className="eyebrow">То, ради чего мы работаем</p><h2>Больше движения.<br/>Больше <em>вашей жизни.</em></h2><p className="result-description">У каждого — своя цель восстановления. Вместе определяем, к каким занятиям вы хотите вернуться, и работаем над движениями, которые для этого нужны.</p><div className="result-words"><span>Гулять и передвигаться</span><span>Работать и заниматься делами</span><span>Возвращаться к тренировкам</span><span>Сохранять самостоятельность</span></div></section>
 <section className="section panel reveal" id="reviews"><Heading label="Истории и отзывы" title={<>За каждым движением —<br/><em>своя история.</em></>}/><div className="review-grid"><Photo label="Фото / видео · история пациента"/><div className="review-placeholder"><span className="quote-mark">“</span><h3>Здесь будет история<br/>восстановления пациента</h3><p>Что беспокоило → как проходила работа → какой результат достигнут.</p><span className="muted">Добавим после получения подтверждённого отзыва.</span></div></div><div className="review-short">{[1,2].map(i=><div key={i}>Место для отзыва пациента <span>0{i}</span></div>)}</div></section>
 <section className="section panel reveal" id="prices"><Heading label="Стоимость" title={<>Начните<br/><em>с консультации.</em></>}><p>Персональная программа рассчитывается после знакомства с вашей задачей.</p></Heading><div className="prices-grid"><article className="price-card green-surface"><span className="eyebrow">Первый шаг</span><h3>Первичный приём</h3><p>Консультация специалиста и определение дальнейшего маршрута.</p><strong>Стоимость уточняется</strong><ContactButton className="button light">Узнать стоимость ↗</ContactButton></article><article className="price-card"><span className="eyebrow">Ваш маршрут</span><h3>Индивидуальная программа</h3><p>Состав, длительность и стоимость зависят от состояния и целей восстановления.</p><strong>После консультации</strong></article><article className="price-card"><span className="eyebrow">Регулярная работа</span><h3>Абонементы</h3><p>Для регулярных программ восстановления и поддержки результата.</p><strong>Подберём вместе</strong></article></div><div className="certificate-row"><div><h3>Сертификаты</h3><p>Номиналы и условия использования уточняются.</p></div><ContactButton className="text-link">Узнать подробнее ↗</ContactButton></div></section>
 <section className="section panel faq-section reveal" id="faq"><div><p className="eyebrow">Вопросы и ответы</p><h2>Давайте<br/><em>разберёмся.</em></h2><p>Самое важное перед первым обращением.</p></div><Accordion defaultValue={['0']}>{[
 ['Основные сведения о медицинской организации','Юридическое наименование, реквизиты, адрес и сведения о медицинской организации будут добавлены после предоставления центром.'],
 ['Лицензия на осуществление медицинской деятельности','Лицензия и сведения о разрешённых видах медицинской деятельности будут доступны после предоставления документов центром.'],
 ['Правила предоставления платных медицинских услуг','Здесь будут опубликованы утверждённые центром правила предоставления платных медицинских услуг.'],
 ['Образцы документов для скачивания и ознакомления пациентами','Добавим образцы договора, согласий и других документов для ознакомления и скачивания после их предоставления центром.'],
 ['Контролирующие органы и экстренные службы','Контактные данные контролирующих органов и экстренных служб будут добавлены после подтверждения центром.'],
 ['Порядок оформления официальных претензий, их направления в адрес клиники и ответов на них администрацией клиники','Утверждённый порядок оформления и направления претензий, контакты для обращений и сроки ответов администрации будут опубликованы после предоставления центром.'],
 ['В чем разница между врачом терапевтом по физической реабилитации, врачом-реабилитологом, врачом спортивной медицины и ЛФК?','Подробное описание квалификации и задач каждого специалиста добавим после согласования с медицинской командой центра. Поможем выбрать специалиста при записи.'],
 ['К кому мне записаться на первичный прием? Как выбрать нужного специалиста?','Расскажите, что вас беспокоит, и мы поможем определить, с какого специалиста начать. Оставьте имя, телефон и почту через кнопку обратной связи.'],
 ['Что нужно взять на первичный прием?','Если у вас есть заключения, выписки и результаты обследований, подготовьте их к консультации. Полный список необходимых документов уточним перед визитом.'],
 ['Есть ли платная или бесплатная парковка у реабилитационного центра?','Условия платной и бесплатной парковки уточняются. Информация будет добавлена после подтверждения центром.'],
 ['Дни и часы работы клиники','Дни и часы работы будут добавлены после подтверждения расписания центром.']
 ].map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="section panel reveal" id="contacts"><Heading label="Контакты" title={<>Мы <em>рядом.</em></>}/><div className="contacts-grid"><div className="map-placeholder"><span className="map-pin"><span/></span><p>Здесь будет карта проезда</p></div><div className="contact-details"><div className="contact-city"><h3>Москва</h3><p>Адрес и удобный маршрут добавим позже.</p></div><div><span>Адрес</span><p>Москва · адрес уточняется</p></div><div><span>Телефон и email</span><p>Контакты будут добавлены</p></div><div><span>Режим работы и парковка</span><p>Информация уточняется</p></div><div className="contact-directions"><span>Схема проезда</span><p>От метро «Полежаевская», ТЦ «Авиапарк» и метро «Сокол». Схемы добавим после подтверждения адреса.</p></div><ContactButton className="text-link">Задать вопрос ↗</ContactButton></div></div></section>
 <footer className="panel"><div className="footer-top"><Brand full/><p>Свобода движения<br/>с опорой на будущее.</p><a className="top-link" href="#" aria-label="Наверх">↑</a></div><div className="footer-links"><div><b>О центре</b><a href="#about">О центре</a><a href="#directions">Направления</a><a href="#team">Специалисты</a><a href="#space">Пространство</a></div><div><b>Информация</b><a href="#prices">Стоимость</a><a href="#reviews">Отзывы</a><a href="#faq">Вопросы и ответы</a><a href="#contacts">Контакты</a></div><div className="documents"><b>Пациентам</b><ul>{["Сведения о медицинской организации","Лицензия","Правила платных медицинских услуг","Публичная оферта","Образцы документов для пациентов","Политика конфиденциальности","Условия и политика обработки персональных данных","Согласия на обработку персональных данных","Форма ИДС","Отказ от медицинского вмешательства","Политика cookies","Контролирующие органы и экстренные службы","Порядок подачи и рассмотрения претензий"].map(doc=><li key={doc}>{doc}</li>)}</ul><small>Документы будут добавлены.</small></div></div><div className="footer-bottom"><span>© 2026 Точка опоры</span><span>Центр реабилитации позвоночника и суставов</span></div></footer>
 </>;
}
